#!/usr/bin/env python3
"""Render the canonical agent Markdown tree into the checked-in static docs shell."""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from urllib.parse import quote, urlsplit, urlunsplit


REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
SOURCE_ROOT = DOCS / "agents"
ASSET_ROOT = SOURCE_ROOT / "_assets"
GENERATED_MARKER = "<!-- Generated by scripts/build-agent-docs.py; do not edit. -->"


@dataclass(frozen=True)
class Page:
    category: str
    label: str
    source: str
    description: str

    @property
    def source_path(self) -> Path:
        return SOURCE_ROOT / self.source

    @property
    def output_path(self) -> Path:
        return self.source_path.with_suffix(".html")

    @property
    def url(self) -> str:
        return PurePosixPath(self.source).with_suffix(".html").as_posix()


PAGES = (
    Page("Start here", "Overview", "index.md", "Choose the right Voidscape path for an agent task."),
    Page("Start here", "Install", "install.md", "Install the skill and verify local readiness."),
    Page("Start here", "Quick start", "quick-start.md", "Complete a key-free inspect, preview, and read."),
    Page("Start here", "Concepts", "concepts.md", "Understand sources, evidence, gates, and citations."),
    Page("Operate", "Workflow and protocol", "workflow.md", "Drive the guided flow and raw reader protocol safely."),
    Page("Operate", "Agent automation", "automation.md", "Coordinate deterministic commands without weakening consent."),
    Page("Operate", "Observe and capture", "observe-and-capture.md", "Capture an explicit image or clip before a governed read."),
    Page("Readers", "Video and audio", "readers/video-audio.md", "Prepare frames and timestamped transcript evidence."),
    Page("Readers", "Images and carousels", "readers/images.md", "Prepare ordered, byte-preserving local image evidence."),
    Page("Readers", "Articles and RSS/Atom", "readers/articles-rss.md", "Prepare ordered text evidence from documents and feeds."),
    Page("Readers", "Chat exports", "readers/chats-whatsapp.md", "Turn a local WhatsApp-style export into citable message evidence."),
    Page("Agent environments", "Harness support", "harnesses.md", "Separate harness features from verified Voidscape behavior."),
    Page("Agent environments", "Constraints and permissions", "constraints.md", "Apply the non-negotiable consent and privacy rules."),
    Page("Agent environments", "Connectors", "connectors.md", "Connect harness sources to the reading core without new trust."),
    Page("Agent environments", "Harness skill kit", "harness-kit.md", "Copy-and-adapt evidence-riding skill templates."),
    Page("Capture adapters", "Instagram", "capture-adapters/instagram.md", "Use the development-only Instagram queue helper."),
    Page("Capture adapters", "Instagram follow audit", "capture-adapters/ig-follow-audit.md", "Diff follow exports into a citable review report."),
    Page("Capture adapters", "YouTube", "capture-adapters/youtube.md", "Use the development-only private-playlist adapter."),
    Page("Reference", "Roadmap status", "roadmap-status.md", "Distinguish shipped, dev-only, planned, and parked work."),
    Page("Reference", "References", "references.md", "Trace agent documentation back to canonical evidence."),
    Page("Help", "Troubleshooting", "troubleshooting.md", "Diagnose common failures without bypassing a gate."),
)

PAGE_BY_SOURCE = {page.source: page for page in PAGES}
HEADING_RE = re.compile(r"^(#{1,4})\s+(.+?)\s*$")
LIST_RE = re.compile(r"^(\s*)([-*]|\d+\.)\s+(.+)$")
TABLE_SEPARATOR_RE = re.compile(r"^\s*\|?\s*:?-{3,}")
FENCE_RE = re.compile(r"^\s*```\s*([\w+-]*)\s*$")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
CODE_RE = re.compile(r"`([^`]+)`")
STRONG_RE = re.compile(r"\*\*(.+?)\*\*")
BACK_LINK_RE = re.compile(r"^\[Back to agent docs\]\([^)]+\)\s*·?\s*", re.IGNORECASE)


def _slug(value: str) -> str:
    value = re.sub(r"`([^`]+)`", r"\1", value)
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"<[^>]+>", "", value)
    value = value.casefold().replace("&", " and ")
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "section"


def _relative_url(current_output: Path, target: Path) -> str:
    return Path(os.path.relpath(target, current_output.parent)).as_posix()


def _rewrite_link(url: str, current_source: Path) -> str:
    parsed = urlsplit(url)
    if parsed.scheme or parsed.netloc or url.startswith(("#", "mailto:")):
        return url
    target = (current_source.parent / parsed.path).resolve()
    try:
        relative_source = target.relative_to(SOURCE_ROOT.resolve())
    except ValueError:
        relative_source = None
    if relative_source is not None:
        if target.suffix.casefold() != ".md":
            return url
        current_output = current_source.with_suffix(".html")
        target_output = (SOURCE_ROOT / relative_source).with_suffix(".html")
        path = _relative_url(current_output, target_output)
        return urlunsplit(("", "", path, parsed.query, parsed.fragment))

    # The public deployment serves docs/, not repository-root files. Keep source and
    # contract links usable by sending those resolved repository paths to GitHub.
    try:
        repository_path = target.relative_to(REPO.resolve())
    except ValueError:
        return url
    if not target.is_file():
        return url
    github_path = quote(repository_path.as_posix(), safe="/")
    return urlunsplit(("https", "github.com", f"/RikepilB/void-scape/blob/main/{github_path}", parsed.query, parsed.fragment))


def _inline(value: str, current_source: Path) -> str:
    tokens: dict[str, str] = {}

    def stash(rendered: str) -> str:
        key = f"@@VOIDSCAPE_TOKEN_{len(tokens)}@@"
        tokens[key] = rendered
        return key

    def code(match: re.Match[str]) -> str:
        return stash(f"<code>{html.escape(match.group(1))}</code>")

    def link(match: re.Match[str]) -> str:
        label = html.escape(match.group(1))
        label = CODE_RE.sub(r"<code>\1</code>", label)
        href = _rewrite_link(match.group(2), current_source)
        attrs = ""
        if href.startswith(("http://", "https://")):
            attrs = ' target="_blank" rel="noreferrer"'
        return stash(f'<a href="{html.escape(href, quote=True)}"{attrs}>{label}</a>')

    value = LINK_RE.sub(link, value)
    value = CODE_RE.sub(code, value)
    value = html.escape(value)
    value = STRONG_RE.sub(r"<strong>\1</strong>", value)
    for key, rendered in tokens.items():
        value = value.replace(key, rendered)
    return value


def _is_block_start(lines: list[str], index: int) -> bool:
    line = lines[index]
    stripped = line.strip()
    if not stripped:
        return True
    if HEADING_RE.match(line) or FENCE_RE.match(line) or LIST_RE.match(line):
        return True
    if stripped == "---" or stripped.startswith("> "):
        return True
    return index + 1 < len(lines) and "|" in line and TABLE_SEPARATOR_RE.match(lines[index + 1]) is not None


def _table_cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def _render_markdown(source: Path) -> tuple[str, str, list[tuple[int, str, str]]]:
    lines = source.read_text(encoding="utf-8").splitlines()
    title = source.stem.replace("-", " ").title()
    body: list[str] = []
    toc: list[tuple[int, str, str]] = []
    used_slugs: dict[str, int] = {}
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if not stripped:
            i += 1
            continue

        heading = HEADING_RE.match(line)
        if heading:
            level = len(heading.group(1))
            text = heading.group(2).strip()
            if level == 1:
                title = re.sub(r"[`*_]", "", text)
                i += 1
                continue
            base_slug = _slug(text)
            count = used_slugs.get(base_slug, 0)
            used_slugs[base_slug] = count + 1
            anchor = base_slug if count == 0 else f"{base_slug}-{count + 1}"
            toc.append((level, re.sub(r"[`*_]", "", text), anchor))
            body.append(
                f'<h{level} id="{anchor}">{_inline(text, source)}'
                f'<a class="heading-anchor" href="#{anchor}" aria-label="Link to {html.escape(text, quote=True)}">#</a>'
                f"</h{level}>"
            )
            i += 1
            continue

        fence = FENCE_RE.match(line)
        if fence:
            language = fence.group(1).casefold()
            code_lines: list[str] = []
            i += 1
            while i < len(lines) and FENCE_RE.match(lines[i]) is None:
                code_lines.append(lines[i])
                i += 1
            if i < len(lines):
                i += 1
            labels = {"powershell": "PowerShell", "bash": "Shell", "json": "JSON", "text": "Protocol"}
            label = labels.get(language, language.upper() if language else "Terminal")
            code_text = "\n".join(code_lines).strip("\n")
            body.append(
                '<div class="code-block">'
                f'<div class="code-meta"><span>{html.escape(label)}</span>'
                '<button class="copy-button" type="button">Copy</button></div>'
                f'<pre><code class="language-{html.escape(language)}">{html.escape(code_text)}</code></pre>'
                "</div>"
            )
            continue

        if i + 1 < len(lines) and "|" in line and TABLE_SEPARATOR_RE.match(lines[i + 1]):
            headers = _table_cells(line)
            i += 2
            rows: list[list[str]] = []
            while i < len(lines) and lines[i].strip() and "|" in lines[i]:
                rows.append(_table_cells(lines[i]))
                i += 1
            rendered_headers = "".join(f"<th scope=\"col\">{_inline(cell, source)}</th>" for cell in headers)
            rendered_rows = []
            for row in rows:
                padded = row + [""] * max(0, len(headers) - len(row))
                rendered_rows.append("<tr>" + "".join(f"<td>{_inline(cell, source)}</td>" for cell in padded[: len(headers)]) + "</tr>")
            body.append(
                '<div class="table-scroll"><table><thead><tr>' + rendered_headers
                + "</tr></thead><tbody>" + "".join(rendered_rows) + "</tbody></table></div>"
            )
            continue

        list_match = LIST_RE.match(line)
        if list_match:
            ordered = list_match.group(2).endswith(".")
            tag = "ol" if ordered else "ul"
            items: list[str] = []
            while i < len(lines):
                match = LIST_RE.match(lines[i])
                if match is None or match.group(2).endswith(".") != ordered:
                    break
                item_parts = [match.group(3).strip()]
                i += 1
                while i < len(lines) and lines[i].strip() and LIST_RE.match(lines[i]) is None and not _is_block_start(lines, i):
                    item_parts.append(lines[i].strip())
                    i += 1
                items.append(" ".join(item_parts))
            body.append(f"<{tag}>" + "".join(f"<li>{_inline(item, source)}</li>" for item in items) + f"</{tag}>")
            continue

        if stripped.startswith("> "):
            quote: list[str] = []
            while i < len(lines) and lines[i].strip().startswith("> "):
                quote.append(lines[i].strip()[2:])
                i += 1
            body.append(f'<aside class="callout">{_inline(" ".join(quote), source)}</aside>')
            continue

        if stripped == "---":
            body.append("<hr>")
            i += 1
            continue

        paragraph = [stripped]
        i += 1
        while i < len(lines) and lines[i].strip() and not _is_block_start(lines, i):
            paragraph.append(lines[i].strip())
            i += 1
        text = " ".join(paragraph)
        source_note = BACK_LINK_RE.sub("", text)
        if source_note != text:
            if source_note:
                body.append(f'<p class="source-note">{_inline(source_note, source)}</p>')
            continue
        css_class = ' class="status-line"' if text.startswith("**Status:**") else ""
        body.append(f"<p{css_class}>{_inline(text, source)}</p>")

    return title, "\n".join(body), toc


def _nav_html(current: Page) -> str:
    groups: list[str] = []
    categories: list[str] = []
    for page in PAGES:
        if page.category not in categories:
            categories.append(page.category)
    for category in categories:
        links = []
        for page in (item for item in PAGES if item.category == category):
            href = _relative_url(current.output_path, page.output_path)
            active = ' class="active" aria-current="page"' if page == current else ""
            links.append(f'<a href="{href}"{active}>{html.escape(page.label)}</a>')
        groups.append(
            '<details class="nav-group" open>'
            f"<summary>{html.escape(category)}</summary>"
            f'<div class="nav-links">{"".join(links)}</div>'
            "</details>"
        )
    manifest_href = _relative_url(current.output_path, SOURCE_ROOT / "manifest.json")
    groups.append(
        '<div class="nav-utility">'
        f'<a href="{manifest_href}"><span>JSON</span> Discovery manifest</a>'
        "</div>"
    )
    return "\n".join(groups)


def _toc_html(toc: list[tuple[int, str, str]]) -> str:
    links = ['<a href="#top" class="toc-level-2">Overview</a>']
    links.extend(
        f'<a href="#{anchor}" class="toc-level-{level}">{html.escape(text)}</a>'
        for level, text, anchor in toc
        if level <= 3
    )
    return "\n".join(links)


def _page_navigation(current: Page) -> str:
    index = PAGES.index(current)
    links = []
    if index > 0:
        previous = PAGES[index - 1]
        href = _relative_url(current.output_path, previous.output_path)
        links.append(f'<a class="previous" href="{href}"><span>Previous</span><strong>← {html.escape(previous.label)}</strong></a>')
    if index < len(PAGES) - 1:
        following = PAGES[index + 1]
        href = _relative_url(current.output_path, following.output_path)
        links.append(f'<a class="next" href="{href}"><span>Next</span><strong>{html.escape(following.label)} →</strong></a>')
    return "".join(links)


def _render_page(page: Page) -> str:
    title, content, toc = _render_markdown(page.source_path)
    css_href = _relative_url(page.output_path, ASSET_ROOT / "docs.css")
    js_href = _relative_url(page.output_path, ASSET_ROOT / "docs.js")
    favicon_href = _relative_url(page.output_path, DOCS / "favicon.svg")
    favicon_png_href = _relative_url(page.output_path, DOCS / "favicon-32.png")
    touch_href = _relative_url(page.output_path, DOCS / "apple-touch-icon.png")
    home_href = _relative_url(page.output_path, DOCS / "index.html")
    guide_href = _relative_url(page.output_path, DOCS / "guide.html")
    docs_home = _relative_url(page.output_path, PAGES[0].output_path)
    docs_root = Path(os.path.relpath(SOURCE_ROOT, page.output_path.parent)).as_posix()
    if docs_root == ".":
        docs_root = ""
    else:
        docs_root += "/"
    toc_links = _toc_html(toc)
    edit_url = f"https://github.com/RikepilB/void-scape/edit/main/docs/agents/{page.source}"
    return f"""<!doctype html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{html.escape(page.description, quote=True)}">
  <title>{html.escape(title)} · Voidscape Agent Docs</title>
  <link rel="icon" type="image/svg+xml" href="{favicon_href}">
  <link rel="icon" type="image/png" sizes="32x32" href="{favicon_png_href}">
  <link rel="apple-touch-icon" sizes="180x180" href="{touch_href}">
  <link rel="stylesheet" href="{css_href}">
</head>
<body data-docs-root="{docs_root}" data-page-url="{page.url}">
  {GENERATED_MARKER}
  <a class="skip-link" href="#main-content">Skip to content</a>
  <header class="docs-header">
    <a class="docs-brand" href="{home_href}" aria-label="Voidscape home">
      <img src="{favicon_href}" alt="" width="26" height="26">
      <span>Voidscape</span><b>Docs</b>
    </a>
    <nav class="header-nav" aria-label="Product navigation">
      <a href="{home_href}">Website</a>
      <a href="{guide_href}">Guide</a>
      <a href="{docs_home}" aria-current="page">Agent docs</a>
    </nav>
    <div class="header-actions">
      <span class="version-badge"><i></i> Current main</span>
      <button class="search-trigger" type="button" data-search-open aria-label="Search documentation">
        <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg>
        <span>Search</span><kbd>Ctrl K</kbd>
      </button>
      <a class="icon-button github-link" href="https://github.com/RikepilB/void-scape" target="_blank" rel="noreferrer" aria-label="Voidscape on GitHub">
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 0 0-3.16 19.49c.5.09.68-.22.68-.48v-1.87c-2.78.6-3.37-1.18-3.37-1.18-.45-1.16-1.11-1.47-1.11-1.47-.91-.62.07-.61.07-.61 1 .07 1.53 1.03 1.53 1.03.9 1.53 2.35 1.09 2.92.83.09-.65.35-1.09.64-1.34-2.22-.25-4.56-1.11-4.56-4.94 0-1.09.39-1.98 1.03-2.68-.1-.25-.45-1.27.1-2.64 0 0 .84-.27 2.75 1.02A9.6 9.6 0 0 1 12 6.82a9.6 9.6 0 0 1 2.5.34c1.91-1.29 2.75-1.02 2.75-1.02.55 1.37.2 2.39.1 2.64.64.7 1.03 1.59 1.03 2.68 0 3.84-2.34 4.68-4.57 4.93.36.31.68.92.68 1.86v2.76c0 .27.18.58.69.48A10 10 0 0 0 12 2Z"/></svg>
      </a>
      <button class="icon-button theme-toggle" type="button" data-theme-toggle aria-label="Switch to light theme">
        <svg class="theme-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"/></svg>
      </button>
      <button class="icon-button menu-toggle" type="button" data-menu-toggle aria-expanded="false" aria-controls="docs-sidebar" aria-label="Open documentation menu">
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>
      </button>
    </div>
  </header>

  <div class="sidebar-scrim" data-menu-scrim hidden></div>
  <div class="docs-layout">
    <aside class="docs-sidebar" id="docs-sidebar" aria-label="Documentation navigation">
      <div class="sidebar-head"><span>Agent documentation</span><button type="button" data-menu-close aria-label="Close documentation menu">×</button></div>
      <nav aria-label="Main documentation">{_nav_html(page)}</nav>
      <footer><span>Local-first evidence</span><span>Protocol 1.0</span></footer>
    </aside>

    <main id="main-content" tabindex="-1">
      <details class="mobile-toc">
        <summary>On this page <span>Overview</span></summary>
        <nav aria-label="On this page">{toc_links}</nav>
      </details>
      <article class="docs-article" id="top">
        <header class="article-header"><span>{html.escape(page.category)}</span><h1>{html.escape(title)}</h1></header>
        {content}
        <div class="article-edit"><a href="{edit_url}" target="_blank" rel="noreferrer">Edit this page on GitHub ↗</a></div>
        <nav class="page-navigation" aria-label="Previous and next pages">{_page_navigation(page)}</nav>
      </article>
    </main>

    <aside class="page-toc" aria-label="On this page">
      <strong>On this page</strong>
      <nav>{toc_links}</nav>
    </aside>
  </div>

  <div class="search-layer" data-search-layer hidden>
    <button class="search-dismiss" type="button" data-search-close tabindex="-1" aria-label="Close search"></button>
    <section class="search-dialog" role="dialog" aria-modal="true" aria-labelledby="search-title">
      <header><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg><label id="search-title" for="docs-search">Search agent docs</label><button type="button" data-search-close aria-label="Close search">Esc</button></header>
      <input id="docs-search" type="search" autocomplete="off" placeholder="Try “approval”, “RSS”, or “exit code”…">
      <div class="search-results" data-search-results role="listbox" aria-label="Search results"></div>
      <footer><span>↑↓ move</span><span>Enter open</span><span>Esc close</span></footer>
    </section>
  </div>
  <script src="{js_href}" defer></script>
</body>
</html>
"""


def _plain_text(source: Path) -> str:
    value = source.read_text(encoding="utf-8")
    value = re.sub(r"```.*?```", " ", value, flags=re.DOTALL)
    value = LINK_RE.sub(r"\1", value)
    # Strip block/list markers without corrupting filenames and CLI identifiers.
    value = re.sub(r"(?m)^\s*(?:#{1,6}\s+|[-*+]\s+|>\s*)", " ", value)
    value = re.sub(r"[*`|\[\]]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def _expected_outputs() -> dict[Path, str]:
    outputs = {page.output_path: _render_page(page) for page in PAGES}
    search_index = [
        {
            "title": page.label,
            "category": page.category,
            "description": page.description,
            "url": page.url,
            "text": _plain_text(page.source_path),
        }
        for page in PAGES
    ]
    outputs[ASSET_ROOT / "search-index.json"] = json.dumps(search_index, ensure_ascii=False, indent=2) + "\n"
    return outputs


def build(check: bool) -> int:
    missing_sources = [str(page.source_path) for page in PAGES if not page.source_path.is_file()]
    missing_assets = [str(path) for path in (ASSET_ROOT / "docs.css", ASSET_ROOT / "docs.js") if not path.is_file()]
    if missing_sources or missing_assets:
        for path in missing_sources + missing_assets:
            print(f"missing: {path}", file=sys.stderr)
        return 1

    drift: list[Path] = []
    for path, expected in _expected_outputs().items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                drift.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")

    if drift:
        for path in drift:
            print(f"out of date: {path.relative_to(REPO)}", file=sys.stderr)
        print("run: python scripts/build-agent-docs.py", file=sys.stderr)
        return 1
    if check:
        print(f"agent docs current: {len(PAGES)} pages")
    else:
        print(f"agent docs built: {len(PAGES)} pages")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated docs differ")
    return build(parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
