"""Regenerate an original F-shaped fixture font; optional developer fontTools only.

No external font or glyph is read. The generated module has no fontTools dependency.
"""
import base64
import io
from pathlib import Path


def main():
    from fontTools.fontBuilder import FontBuilder
    from fontTools.pens.ttGlyphPen import TTGlyphPen

    builder = FontBuilder(1000, isTTF=True)
    builder.setupGlyphOrder([".notdef", "space", "F"])
    builder.setupCharacterMap({32: "space", 70: "F"})
    empty = TTGlyphPen(None).glyph()
    pen = TTGlyphPen(None)
    points = [(100, 0), (100, 700), (600, 700), (600, 600), (220, 600),
              (220, 420), (520, 420), (520, 320), (220, 320), (220, 0)]
    pen.moveTo(points[0])
    for point in points[1:]:
        pen.lineTo(point)
    pen.closePath()
    builder.setupGlyf({".notdef": empty, "space": empty, "F": pen.glyph()})
    builder.setupHorizontalMetrics({".notdef": (700, 0), "space": (350, 0), "F": (700, 100)})
    builder.setupHorizontalHeader(ascent=800, descent=-200)
    builder.setupNameTable({"familyName": "Voidscape Fixture", "styleName": "Regular",
                            "uniqueFontIdentifier": "VoidscapeFixture-1",
                            "fullName": "Voidscape Fixture", "psName": "VoidscapeFixture",
                            "version": "Version 1.0"})
    builder.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    builder.setupPost()
    builder.setupMaxp()
    builder.font.recalcTimestamp = False
    builder.font["head"].created = builder.font["head"].modified = 3406620153
    stream = io.BytesIO()
    builder.save(stream)
    encoded = base64.b64encode(stream.getvalue()).decode("ascii")
    output = Path(__file__).with_name("capture_fixture_font.py")
    output.write_text('"""Original synthetic F glyph; generated by generate_capture_font.py."""\n'
                      'import base64\n\nFONT = base64.b64decode(\n'
                      + ''.join(f'    "{encoded[i:i+88]}"\n' for i in range(0, len(encoded), 88))
                      + ')\n', encoding="utf-8")


if __name__ == "__main__":
    main()
